# Generated by Django 3.2.9 on 2021-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStoreList',
            fields=[
                ('seq', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('regdate', models.CharField(blank=True, db_column='regDate', max_length=20, null=True)),
                ('simplenm', models.CharField(blank=True, db_column='simpleNm', max_length=20, null=True)),
                ('zipcd', models.CharField(blank=True, db_column='zipCd', max_length=10, null=True)),
                ('addr', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('telno', models.CharField(blank=True, db_column='telNo', max_length=15, null=True)),
                ('biztype', models.CharField(blank=True, db_column='bizType', max_length=10, null=True)),
                ('biztypenm', models.CharField(blank=True, db_column='bizTypeNm', max_length=10, null=True)),
                ('biztypedetail', models.CharField(blank=True, db_column='bizTypeDetail', max_length=10, null=True)),
                ('salescd', models.CharField(blank=True, db_column='salesCd', max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'sample_store_list',
                'managed': False,
            },
        ),
    ]
