# Generated by Django 3.2.9 on 2021-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'sample_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleStoreList',
            fields=[
                ('seq', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('simplenm', models.CharField(blank=True, db_column='simpleNm', max_length=20, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'sample_store_list',
                'managed': False,
            },
        ),
    ]
